version: '2'
services:
  leanote:
    image: dreamer1/leanote:latest
    stdin_open: true
    volumes:
    - /opt/svicloud/tools/leanote/conf:/usr/local/bin/leanote/conf
    - /opt/svicloud/tools/leanote/public:/usr/local/bin/leanote/public
    - /opt/svicloud/tools/leanote/mongo_data:/usr/local/bin/leanote/db_data
    tty: true
    ports:
    - 9000:9000/tcp

